name: Publish to Docker Hub

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout Main
              uses: actions/checkout@v3

            - name: Build & Publish to Docker Hub
              uses: elgohr/Publish-Docker-Github-Action@v5
              with:
                  name: bpkennedy/pardes
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
